momentum-xyz/ui-client

src/scenes/widgets/pages/StakingWidget/components/templates/Nominator/Nominator.tsx, src/scenes/widgets/stores/StakingStore/models/PolkadotProviderStore/PolkadotProviderStore.ts, src/shared/services/web3/SubstrateProvider.ts
- Subscriptions for staking data and balance data
=> Subscriptions

src/scenes/widgets/stores/StakingStore/models/ValidatorsStore/ValidatorsStore.ts
=> Validators display

.eslintrc, craco.config.js
As discussed with @PAKovalev I'm pushing here changes that should reduce the number of build warnings and leave mostly the ones that matter.
=> App build improvements - warnings

README.md, src/api/constants/app.variables.ts, src/stores/ConfigStore/ConfigStore.ts
Useful feature for some of local testing
=> Ability to override locally some of app config variables

src/scenes/collaboration/components/EmojiAnimationDock/EmojiAnimationDock.tsx, src/scenes/collaboration/components/EmojiAnimationDock/components/EmojiWithAvatarAnimation/EmojiWithAvatarAnimation.styled.ts
I tweaked the animation of the emoji a little bit.
=> Slight tweaks of the emoji animation

src/scenes/widgets/pages/HelpWidget/HelpWidget.tsx
https://momentum.nifty.pm/l/u9CurUSFiv
Subtask: Close Help section after Sign Up form :: User can not fly.
=> fixed closing help after signup

src/scenes/meeting/pages/MeetingRoomPage/MeetingRoomPage.tsx, src/scenes/meeting/pages/MeetingRoomPage/components/organisms/MuteAllButton/MuteAllButton.tsx, src/scenes/meeting/pages/MeetingRoomPage/components/templates/MeetingUser/MeetingUser.tsx, src/scenes/meeting/stores/MeetingRoomStore/MeetingRoomStore.ts, src/stores/MainStore/models/AgoraStore/AgoraMeetingStore/AgoraMeetingStore.ts
I moved `mute` stuff to the `MeetingRoomStore` and fixed a bug linked to the `Mute` button.
#DEV-1
=> feature(space): mute user

src/stores/RootStore.ts
#DEV-1
The Agora lose connection when user tries to leave space.
=> feature(space): leaving

src/scenes/widgets/pages/HelpWidget/HelpWidget.tsx, src/scenes/widgets/pages/LaunchInitiativeWidget/LaunchInitiativeWidget.tsx, src/scenes/widgets/pages/ProfileMenuWidget/components/TokenRules/TokenRules.tsx, src/ui-kit/organisms/Dialog/Dialog.styled.ts, src/ui-kit/organisms/Dialog/Dialog.tsx
#DEV-1
Proper keyboard control in widgets.
=> feature(unity): movement

src/scenes/home/pages/HomePage/HomePage.styled.ts, src/scenes/home/pages/HomePage/components/templates/ExplorePanel/ExplorePanel.styled.ts, src/scenes/home/pages/HomePage/components/templates/ExplorePanel/ExplorePanel.tsx, src/scenes/home/pages/HomePage/components/templates/OnlineUsersPanel/OnlineUsersPanel.styled.ts, src/scenes/home/pages/HomePage/components/templates/OnlineUsersPanel/OnlineUsersPanel.tsx
#DEV-1
Home page. Cursor-pointer fixed in `ExpandableLayout`.
=> feature(home page): cursor-pointer

src/scenes/unity/pages/UnityPage/UnityPage.tsx, src/scenes/widgets/pages/MusicPlayerWidget/components/UnityVolumeController/UnityVolumeController.tsx, src/stores/MainStore/models/UnityStore/UnityStore.ts
#DEV-1
Unity volume and default volume fixing.
=> Bugfix/dev 1/unity default volume

src/core/models/OnlineUsersList/OnlineUsersList.ts, src/scenes/collaboration/pages/DashboardPage/components/templates/InviteToSpaceMenu/InviteToSpaceMenu.tsx, src/stores/MainStore/models/AgoraStore/AgoraStageModeStore/AgoraStageModeStore.ts, src/stores/MainStore/models/AgoraStore/AgoraStore.ts, src/ui-kit/organisms/OnlineUsersList/OnlineUsersList.tsx
https://momentum.nifty.pm/l/_W7FY!D7!e2l
• If user joins the space, or accepts the invite and joins the space, the name of the user is removed from that list with people available for invite
=> Feature/dev 25/invite people to space

src/core/utils/router.utils.tsx, src/scenes/App.routes.tsx, src/scenes/App.tsx, src/scenes/AppLayers.tsx, src/scenes/collaboration/Collaboration.tsx, src/scenes/spaceAdmin/SpaceAdmin.routes.tsx, src/scenes/spaceAdmin/SpaceAdmin.tsx, src/scenes/storyBook/StoryBook.tsx, src/scenes/worldBuilder/WorldBuilder.tsx
#DEV-33
1. Now FE uses chunks.
2. Space admin routes fixed.
[https://momentum.nifty.pm/l/s2xS6B4PYNbW](https://momentum.nifty.pm/l/s2xS6B4PYNbW)
=> Feature/dev 33/chunks

src/ui-kit/molecules/ToastContent/ToastContent.tsx, src/ui-kit/organisms/PanelLayout/PanelLayout.tsx
https://momentum.nifty.pm/l/u9CurUSFiv
subtask: To change isCloseButton to showCloseButton
=> showCloseButton only

craco.config.js, package.json, yarn.lock
#DEV-1
Compression of js & css files was added.
=> feature(main.js): gzip

src/core/constants/routePaths.constants.ts, src/scenes/App.routes.tsx, src/scenes/auth/pages/WorldBuilderLoginPage/WorldBuilderLoginPage.styled.ts, src/scenes/auth/pages/WorldBuilderLoginPage/WorldBuilderLoginPage.tsx, src/scenes/auth/pages/WorldBuilderLoginPage/components/index.ts, src/scenes/auth/pages/WorldBuilderLoginPage/components/templates/WorldBuilderWalletError/WorldBuilderWalletError.styled.ts, src/scenes/auth/pages/WorldBuilderLoginPage/components/templates/WorldBuilderWalletError/WorldBuilderWalletError.tsx, src/scenes/auth/pages/WorldBuilderLoginPage/components/templates/WorldBuilderWalletError/index.ts, src/scenes/auth/pages/WorldBuilderLoginPage/components/templates/index.ts, src/scenes/auth/pages/WorldBuilderLoginPage/index.ts, src/scenes/worldBuilder/pages/WorldBuilderStartPage/WorldBuilderStartPage.tsx, src/shared/services/i18n/locales/en-gb.ts
Added new WorldBuilderLoginPage and removed guest login from it.
Nifty: https://momentum.nifty.pm/l/S9CAYke0Fe
=> Feature/wb 18/remove guest login when in world builder

src/ui-kit/atoms/Portal/Portal.ts, src/ui-kit/hooks/useResize.tsx, src/ui-kit/hooks/useScroll.ts, src/ui-kit/molecules/ShowMoreText/ShowMoreText.tsx, src/ui-kit/organisms/OnlineUsersList/OnlineUsersList.tsx, src/ui-kit/organisms/OnlineUsersList/components/UserItem/UserItem.tsx
Fixing react-hooks/exhaustive-deps- adding some missing deps and refactoring related to others.
#BUG-1
https://momentum.nifty.pm/l/u9CurUSFiv
=> Fixing react-hooks/exhaustive-deps

src/scenes/collaboration/pages/DashboardPage/components/templates/Dashboard/components/TileItem/components/TileDetail.styled.ts, src/scenes/collaboration/pages/DashboardPage/components/templates/Dashboard/components/TileItem/components/TileDetail.tsx, src/scenes/collaboration/pages/DashboardPage/components/templates/TileForm/TileForm.styled.ts, src/scenes/collaboration/pages/DashboardPage/components/templates/TileForm/components/ImageTileForm/ImageTileForm.styled.ts, src/scenes/collaboration/pages/DashboardPage/components/templates/TileForm/components/TextTileForm/TextTileForm.styled.ts, src/scenes/collaboration/pages/DashboardPage/components/templates/TileForm/components/TextTileForm/TextTileForm.tsx, src/scenes/collaboration/pages/DashboardPage/components/templates/TileForm/components/VideoTileForm/VideoTileForm.styled.ts, src/scenes/unity/pages/UnityPage/UnityPage.tsx, src/ui-kit/atoms/Text/Text.styled.ts, src/ui-kit/organisms/EventItem/EventItem.styled.ts, src/ui-kit/organisms/EventItem/EventItem.tsx, src/ui-kit/organisms/InviteToSpaceContent/InviteToSpaceContent.tsx, src/ui-kit/types/textAlign.type.ts
https://momentum.nifty.pm/l/xzKcal_Z0k
- Make text fields bigger (for better UX to edit text)
https://momentum.nifty.pm/l/hyH7f2vatRpu
- Make the text box bigger for editing
=> Feature/dev 30/text box field

src/scenes/collaboration/pages/ScreenSharePage/ScreenSharePage.tsx, src/scenes/collaboration/stores/ScreenShareStore/ScreenShareStore.ts, src/stores/MainStore/models/AgoraStore/AgoraScreenShareStore/AgoraScreenShareStore.ts
Fixed screensharing when canceling or no permissions.
Nifty: https://momentum.nifty.pm/l/u9CurUSFiv
=> fixed screensharing when publishing screentrack fails

src/scenes/collaboration/Collaboration.tsx, src/scenes/collaboration/stores/RootCollaborationStore.ts
#DEV-37
Redirecting to the Screenshare page removal.
It may cause another problems linked to plugins.
[https://momentum.nifty.pm/l/6B497zdLYKO](https://momentum.nifty.pm/l/6B497zdLYKO)
=> feature(collaboration): don't redirect user to screenshare page

src/scenes/collaboration/Collaboration.tsx, src/scenes/collaboration/pages/DashboardPage/DashboardPage.tsx, src/scenes/collaboration/stores/RootCollaborationStore.ts
https://momentum.nifty.pm/l/TkSvNl6nY2
User is connected to wrong space in chat after failing to join gathering event
=> not init text chat in private space

src/scenes/unity/pages/UnityPage/UnityPage.tsx
https://momentum.nifty.pm/l/u9CurUSFiv
Join gathering. Chat is not active
=> checking current location before join gathering

src/api/repositories/emojiRepository/emojiRepository.api.ts, src/api/repositories/emojiRepository/emojiRepository.api.types.ts, src/scenes/widgets/stores/EmojiStore/EmojiStore.tsx, src/scenes/widgets/stores/HelpStore/HelpStore.ts
I added the support of the new format but left the old one as well to make the transition easier.
#AT-75
https://momentum.nifty.pm/l/0lSXwe_FdIvc
=> Support new format of Space-Emoji EP with temp legacy support of the old one

src/core/models/Space/Space.ts, src/scenes/spaceAdmin/pages/SpaceAdminPage/components/templates/SubSpacesPanel/components/AddSubSpaceDialog/AddSubSpaceDialog.tsx, src/shared/services/i18n/locales/en-gb.ts
Adding subspace sent an empty post request, I have fixed that
Nifty: https://momentum.nifty.pm/l/VC3juVKeTo subtask: Admin panel: create subspace error
=> Fixed adding subspace not working

src/scenes/collaboration/Collaboration.tsx, src/scenes/collaboration/pages/StageModePage/components/molecules/StageModePopup/StageModePopup.tsx, src/scenes/collaboration/pages/StageModePage/components/organisms/StageModePopupQueue/StageModePopupQueue.tsx, src/scenes/collaboration/pages/StageModePage/components/templates/InvitedOnStageDialog/InvitedOnStageDialog.tsx, src/scenes/collaboration/pages/StageModePage/components/templates/StageModeGuest/StageModeGuest.styled.ts, src/scenes/collaboration/pages/StageModePage/components/templates/StageModeGuest/StageModeGuest.tsx, src/scenes/collaboration/pages/StageModePage/components/templates/StageModeModerator/StageModeModerator.tsx, src/scenes/collaboration/pages/StageModePage/components/templates/StageModeModerator/components/RemoveParticipantFromStageDialog/RemoveParticipantFromStageDialog.styled.ts, src/scenes/collaboration/pages/StageModePage/components/templates/StageModeModerator/components/RemoveParticipantFromStageDialog/RemoveParticipantFromStageDialog.tsx, src/scenes/meeting/pages/MeetingRoomPage/MeetingRoomPage.tsx, src/scenes/meeting/pages/MeetingRoomPage/components/templates/StageModeUser/StageModeUser.tsx, src/shared/services/i18n/locales/en-gb.ts, src/stores/MainStore/models/AgoraStore/AgoraStageModeStore/AgoraStageModeStore.ts
- Fixed the go on stage button showing up for guests when stage is full.
- Fixed the placement for stage mode stats 
- Fixed the layout of remove user off stage dialog
=> Final Stage mode UI fixes

src/scenes/widgets/pages/StageModePIPWidget/StageModePIPWidget.styled.ts
Changed initial position of stage mode picture-in-picture.
[Nifty task](https://momentum.nifty.pm/l/1NVhIBdg!eJrp)
=> Changed initial position of stage mode PIP

src/scenes/collaboration/stores/RootCollaborationStore.ts
#DEV-66
Investigate the issue with Miro and Google Docs after the refactoring.
[https://momentum.nifty.pm/l/_1RSmecTNX](https://momentum.nifty.pm/l/_1RSmecTNX)
=> feature(space): don't stop miro & google drive

src/scenes/collaboration/Collaboration.tsx, src/scenes/collaboration/components/StreamChat/Chat.styled.ts, src/scenes/collaboration/components/StreamChat/index.ts, src/scenes/collaboration/pages/DashboardPage/components/templates/Dashboard/Dashboard.tsx, src/scenes/collaboration/pages/GoogleDrivePage/GoogleDrivePage.tsx, src/scenes/collaboration/pages/LiveStreamPage/LiveStreamPage.tsx, src/scenes/collaboration/pages/MiroBoardPage/MiroBoardPage.tsx, src/scenes/collaboration/pages/ScreenSharePage/ScreenSharePage.tsx, src/scenes/collaboration/pages/StageModePage/StageModePage.tsx, src/scenes/collaboration/pages/StageModePage/components/templates/StageModeGuest/StageModeGuest.tsx, src/scenes/collaboration/pages/StageModePage/components/templates/StageModeModerator/StageModeModerator.tsx
Enabled new chat in all Space tabs (except for Calendar)
=> hotfeature - Stream Chat - part 2

packages/app/src/core/constants/routePaths.constants.ts, packages/app/src/scenes/App.routes.tsx, packages/app/src/scenes/collaboration/pages/DashboardPage/DashboardPage.tsx, packages/app/src/scenes/collaboration/pages/StageModePage/components/templates/StageModeModerator/StageModeModerator.tsx, packages/app/src/scenes/collaboration/stores/RootCollaborationStore.ts, packages/app/src/scenes/flyWithMe/index.ts, packages/app/src/scenes/flyWithMe/pages/FlyWithMePage/FlyWithMePage.tsx, packages/app/src/scenes/flyWithMe/pages/FlyWithMePage/index.ts, packages/app/src/scenes/flyWithMe/pages/index.ts, packages/app/src/scenes/unity/pages/UnityPage/components/atoms/PathObserver/PathObserver.tsx, packages/app/src/shared/services/i18n/locales/en-gb.ts, packages/ui-kit/src/atoms/Button/Button.tsx, packages/ui-kit/src/atoms/IconSvg/IconSvg.styled.ts, packages/ui-kit/src/atoms/IconSvg/IconSvg.tsx, yarn.lock
#FWM-13
Fly with me MVP space constraints.
[https://momentum.nifty.pm/l/KKNp1ZtLRlJ](https://momentum.nifty.pm/l/KKNp1ZtLRlJ)
=> Feature/fwm 13/space constrains

src/scenes/collaboration/components/StreamChat/Chat.styled.ts, src/scenes/collaboration/components/StreamChat/Chat.tsx, src/scenes/collaboration/stores/StreamChatStore/StreamChatStore.ts, src/scenes/widgets/Widgets.tsx, src/scenes/widgets/pages/WorldChatWidget/WorldChatWidget.styled.ts, src/scenes/widgets/pages/WorldChatWidget/WorldChatWidget.tsx, src/shared/services/i18n/locales/en-gb.ts, src/shared/services/unity/UnityService.tsx, src/stores/MainStore/models/UnityStore/UnityStore.ts, src/stores/RootStore.ts
=> hotfeature - Stream Chat - part 3

src/scenes/collaboration/components/StreamChat/Chat.styled.ts, src/scenes/collaboration/stores/StreamChatStore/StreamChatStore.ts, src/scenes/widgets/Widgets.styled.ts, src/scenes/widgets/Widgets.tsx, src/scenes/widgets/pages/ProfileWidget/components/templates/MyProfileEditor/MyProfileEditor.tsx, src/scenes/widgets/pages/WorldChatWidget/WorldChatWidget.tsx
Unread messages count, still not working avatar update, visual improvements
=> hotfeature - Stream Chat - part 4

src/scenes/collaboration/stores/StreamChatStore/StreamChatStore.ts, src/scenes/widgets/Widgets.styled.ts, src/ui-kit/templates/SpaceTopBar/components/RightSection/RightSection.styled.ts
Just an orange dot
The number is a bit unreliable so we use just a dot instead
=> feat(stream-chat): replace the exact number of unread messages with dot

packages/app/src/api/repositories/dashboardRepository/dashboardRepository.api.ts, packages/app/src/api/repositories/dashboardRepository/dashboardRepository.api.types.ts, packages/app/src/core/models/Tile/Tile.ts, packages/app/src/scenes/collaboration/stores/DashboardStore/models/TileFormStore/TileFormStore.ts
https://momentum.nifty.pm/l/iuM4wDwSx4x2
Fix type errors in TileFormStore
=> tile form store type fixes

src/scenes/collaboration/components/StreamChat/Chat.tsx, src/scenes/collaboration/stores/StreamChatStore/StreamChatStore.ts
We were using improper function for this operation that didn't work - client.upsertUser() seems the right one
#DEV-100
=> Release 0.21: Permanent Chat improvements 

src/api/repositories/agoraRepository/agoraRepository.api.endpoints.ts, src/api/repositories/agoraRepository/agoraRepository.api.ts, src/api/repositories/agoraRepository/agoraRepository.api.types.ts, src/core/types/posBusEvent.type.ts, src/core/types/posBusMessage.type.ts, src/scenes/collaboration/pages/ScreenSharePage/ScreenSharePage.tsx, src/scenes/collaboration/stores/ScreenShareStore/ScreenShareStore.ts, src/scenes/meeting/pages/PosBusEventsPage/PosBusEventsPage.tsx, src/shared/services/posBus/PosBusService.tsx, src/stores/MainStore/models/AgoraStore/AgoraScreenShareStore/AgoraScreenShareStore.ts
https://momentum.nifty.pm/l/gYH2thldes
Automatically redirecting users in space when screen sharing starts
=> screen share start redirect

packages/app/src/api/repositories/agoraRepository/agoraRepository.api.endpoints.ts, packages/app/src/api/repositories/agoraRepository/agoraRepository.api.ts, packages/app/src/api/repositories/agoraRepository/agoraRepository.api.types.ts, packages/app/src/core/types/posBusEvent.type.ts, packages/app/src/core/types/posBusMessage.type.ts, packages/app/src/scenes/collaboration/pages/ScreenSharePage/ScreenSharePage.tsx, packages/app/src/scenes/collaboration/stores/ScreenShareStore/ScreenShareStore.ts, packages/app/src/scenes/meeting/pages/PosBusEventsPage/PosBusEventsPage.tsx, packages/app/src/shared/services/posBus/PosBusService.tsx
https://momentum.nifty.pm/l/gYH2thldes
Automatically redirecting users in space when screensharing starts
=> screen share: redirects when starts

packages/app/src/scenes/widgets/pages/HelpWidget/components/Momentum/Momentum.styled.ts, packages/app/src/scenes/widgets/pages/HelpWidget/components/Momentum/Momentum.tsx, packages/app/src/shared/services/i18n/locales/en-gb.ts
#FWM-46
Help Section. Momentum Space button is disabled during Fly with me is active.
[https://momentum.nifty.pm/l/rkRjWNRhzu](https://momentum.nifty.pm/l/rkRjWNRhzu)
=> feature(fly with me): Help section

packages/app/src/scenes/widgets/pages/ProfileMenuWidget/components/Setting/Setting.tsx, packages/app/src/scenes/widgets/pages/ProfileWidget/ProfileWidget.styled.ts, packages/app/src/scenes/widgets/pages/ProfileWidget/components/organisms/UserSpaceList/UserSpaceList.styled.ts, packages/app/src/scenes/widgets/pages/ProfileWidget/components/organisms/UserSpaceList/UserSpaceList.tsx, packages/app/src/scenes/widgets/pages/ProfileWidget/components/organisms/UserSpaceList/components/UserSpaceItem/UserSpaceItem.styled.ts, packages/app/src/scenes/widgets/pages/ProfileWidget/components/organisms/UserSpaceList/components/UserSpaceItem/UserSpaceItem.tsx, packages/app/src/scenes/widgets/pages/ProfileWidget/components/templates/MyProfileView/MyProfileView.styled.ts, packages/app/src/scenes/widgets/pages/ProfileWidget/components/templates/MyProfileView/MyProfileView.tsx, packages/app/src/scenes/widgets/pages/ProfileWidget/components/templates/UserProfileView/UserProfileView.styled.ts, packages/app/src/scenes/widgets/pages/ProfileWidget/components/templates/UserProfileView/UserProfileView.tsx
#DEV-103
Styling issues on the Profile widget.
[https://momentum.nifty.pm/l/gze7SWKWGF](https://momentum.nifty.pm/l/gze7SWKWGF)
=> feature(Profile widget): styling issues

packages/app/src/scenes/meeting/Meeting.tsx, packages/app/src/scenes/meeting/pages/MeetingRoomPage/MeetingRoomPage.tsx, packages/app/src/scenes/meeting/pages/MeetingRoomPage/components/templates/MeetingUser/MeetingUser.styled.ts, packages/app/src/scenes/meeting/pages/MeetingRoomPage/components/templates/MeetingUser/MeetingUser.tsx, packages/app/src/stores/MainStore/models/AgoraStore/AgoraMeetingStore/AgoraMeetingStore.ts, packages/app/src/stores/MainStore/models/AgoraStore/AgoraStore.ts
Potential fix agora videos showing transparent videos and showing streams if limit is reached.
[Nifty Link](https://momentum.nifty.pm/l/mzijAJsvyS8)
=> feature(app): Potential fix for normal meeting

packages/app/src/scenes/App.styled.tsx, packages/app/src/static/styles/reset.scss
https://momentum.nifty.pm/l/0jgWhLymRdzB
make hyperlinks green
=> app: global style for hyperlinks

packages/app/src/scenes/collaboration/components/EmojiAnimationDock/components/MegamojiAnimation/MegamojiAnimation.styled.ts, packages/app/src/scenes/meeting/pages/MeetingRoomPage/MeetingRoomPage.tsx, packages/app/src/scenes/meeting/pages/MeetingRoomPage/components/templates/MeetingUser/MeetingUser.tsx
https://momentum.nifty.pm/l/LWO5xQxL72M
Make MEGA-moji bigger in 2D spaces
Also a change in access to kick/remote users in meeting only for admins
=> app: design/access improvements

packages/app/src/scenes/collaboration/components/EmojiAnimationDock/EmojiAnimationDock.tsx, packages/app/src/scenes/collaboration/components/EmojiAnimationDock/components/MegamojiAnimation/MegamojiAnimation.styled.ts, packages/app/src/scenes/collaboration/components/EmojiAnimationDock/components/MegamojiAnimation/MegamojiAnimation.tsx, packages/app/src/scenes/meeting/pages/MeetingRoomPage/MeetingRoomPage.tsx, packages/app/src/scenes/meeting/pages/MeetingRoomPage/components/organisms/MuteAllButton/MuteAllButton.tsx
https://momentum.nifty.pm/l/LWO5xQxL72M
Mega emoji size position
Mute button access for admins only
=> Feature/at 91/2 d bigger mega emoji

packages/app/src/scenes/flight/pages/FlyWithMePage/FlyWithMePage.tsx, packages/app/src/scenes/unity/pages/UnityPage/UnityPage.tsx
#FWM-51
Don't show GaT invitation if user is in Fly with me.
[https://momentum.nifty.pm/l/X40lg0yGj0](https://momentum.nifty.pm/l/X40lg0yGj0)
=> feature(fly with me): skip GaT requests

packages/app/src/core/constants/routePaths.constants.ts, packages/app/src/scenes/widgets/Widgets.tsx, packages/app/src/scenes/widgets/pages/LiveStreamPIPWidget/LiveStreamPIPWidget.tsx
#FWM-50
Broadcasting buttons buttons must not trigger disengage  from flight.
[https://momentum.nifty.pm/l/RqKz9YT7TE](https://momentum.nifty.pm/l/RqKz9YT7TE)
=> feature(fly with me): broadcasting

packages/app/src/scenes/collaboration/components/EmojiAnimationDock/EmojiAnimationDock.tsx, packages/app/src/scenes/collaboration/components/EmojiAnimationDock/components/MegamojiAnimation/MegamojiAnimation.styled.ts, packages/app/src/scenes/collaboration/components/EmojiAnimationDock/components/MegamojiAnimation/MegamojiAnimation.tsx
https://momentum.nifty.pm/l/UOyIU7!iKa
Make MEGA-moji bigger in 2D spaces
=> feature(megamoji): design improvements

packages/app/src/stores/MainStore/models/AgoraStore/AgoraStore.ts
=> feature(Stage mode): Joining fixed

packages/app/src/scenes/spaceAdmin/pages/SpaceAdminPage/components/templates/SpaceMembersPanel/SpaceMembersPanel.styled.ts, packages/app/src/scenes/spaceAdmin/pages/SpaceAdminPage/components/templates/TokenRulesPanel/TokenRulesPanel.styled.ts
Scrollable panels in space admin
=> bugfix(app): space admin panel markups

packages/app/src/api/enums/index.ts, packages/app/src/api/enums/spaceSubOptionKey.enum.ts, packages/app/src/api/interfaces/attributeSubValue.interface.ts, packages/app/src/api/interfaces/index.ts, packages/app/src/api/repositories/spaceAttributeRepository/spaceAttribute.api.types.ts, packages/app/src/api/repositories/spaceAttributeRepository/spaceAttributes.api.ts, packages/app/src/api/repositories/spaceOptionRepository/spaceOptionRepository.api.endpoints.ts, packages/app/src/api/repositories/spaceOptionRepository/spaceOptionRepository.api.ts, packages/app/src/api/repositories/spaceOptionRepository/spaceOptionRepository.api.types.ts, packages/app/src/api/repositories/spaceRepository/spaceRepository.api.ts, packages/app/src/scenes/collaboration/Collaboration.tsx, packages/app/src/stores/MainStore/models/PluginsStore/PluginsStore.ts
Part 1 (and hopefully last) of making BE properly integrated with FE
=> Feature/mir 17/chnages to reflect be changes

packages/app/src/api/mapper/index.ts, packages/app/src/api/mapper/spaceAttribute.mapper.ts, packages/app/src/scenes/collaboration/pages/CalendarPage/CalendarPage.tsx, packages/app/src/scenes/collaboration/pages/CollaborationPluginPage/CollaborationPluginPage.tsx, packages/app/src/scenes/collaboration/pages/GoogleDrivePage/GoogleDrivePage.tsx, packages/app/src/scenes/collaboration/pages/LiveStreamPage/LiveStreamPage.tsx, packages/app/src/scenes/collaboration/pages/ScreenSharePage/ScreenSharePage.tsx, packages/app/src/scenes/collaboration/pages/StageModePage/components/templates/StageModeGuest/StageModeGuest.tsx, packages/app/src/scenes/collaboration/pages/StageModePage/components/templates/StageModeModerator/StageModeModerator.tsx, packages/app/src/scenes/collaboration/stores/SpaceStore/SpaceStore.ts
Enter to a space implemented.
Space name comes as sub attribute from BE.
[https://momentum.nifty.pm/l/5zsDCx47!!I](https://momentum.nifty.pm/l/5zsDCx47!!I)
=> Feature/ffu 1/entering space

packages/app/src/api/repositories/userRepository/userRepository.api.types.ts, packages/app/src/api/repositories_OLD/statusRepository/statusRepository.api.types.ts, packages/app/src/api/repositories_OLD/userRepository/userRepository.api.types.ts, packages/app/src/core/models/User/User.ts, packages/app/src/scenes/flight/pages/FlyWithMePage/FlyWithMePage.tsx, packages/app/src/scenes/home/pages/HomePage/components/templates/UserProfilePanel/components/UserProfileView/UserProfileView.tsx, packages/app/src/scenes/storyBook/pages/MoleculesPage/MoleculesPage.tsx, packages/app/src/scenes/unity/pages/UnityPage/UnityPage.tsx, packages/app/src/scenes/widgets/pages/ProfileMenuWidget/components/Menu/Menu.tsx, packages/app/src/stores/SessionStore/SessionStore.ts, packages/core/src/enums/index.ts, packages/core/src/enums/userStatus.enum.ts, packages/ui-kit/package.json, packages/ui-kit/src/molecules/Avatar/Avatar.test.tsx, packages/ui-kit/src/molecules/Avatar/Avatar.tsx
Made packages more independent and removed UserStatusEnum duplication
[Nifty ticket](https://momentum.nifty.pm/l/k15ORUawL!Ta8)
=> Feature/mir 65/decouple packages from each other as much as possible

packages/app/src/api/repositories/spaceRepository/spaceRepository.api.endpoints.ts, packages/app/src/api/repositories/spaceRepository/spaceRepository.api.ts, packages/app/src/api/repositories/spaceRepository/spaceRepository.api.types.ts, packages/app/src/core/types/metadataField.type.ts, packages/app/src/scenes/widgets/Widgets.tsx, packages/app/src/scenes/worldBuilder/pages/WorldBuilderUploadAssetPage/WorldBuilderUploadAssetPage.styled.ts, packages/app/src/scenes/worldBuilder/pages/WorldBuilderUploadAssetPage/WorldBuilderUploadAssetPage.tsx, packages/app/src/scenes/worldBuilder/pages/WorldBuilderUploadAssetPage/index.ts, packages/app/src/scenes/worldBuilder/pages/index.ts, packages/app/src/scenes/worldBuilder/stores/RootWorldBuilderStore.ts, packages/app/src/scenes/worldBuilder/stores/WorldBuilderAssetsStore/WorldBuilderAssetsStore.ts, packages/app/src/scenes/worldBuilder/stores/WorldBuilderAssetsStore/index.ts, packages/app/src/shared/services/i18n/locales/en-gb.ts
#GLI-27
https://momentum.nifty.pm/l/KokyfOmIzLi
It adds a world builder icon opening dialog for uploading asset and setting space name - uploading it will create a new space.
=> Hot Feature v0.22 - Glitch2 - Create Space with Asset
